image: julia:0.6

before_script:
  - apt-get update -qq && apt-get install git hdf5-tools -y
  - julia build_script.jl

default:
  script:
    - julia -e "Pkg.test(\"AeroAcoustics.jl\"; coverage = true)"
    - julia coverage_script.jl
